name: GGADFormer_test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - numpy=1.21.6
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - networkx=2.6.3
  - pandas=1.3.5
  - matplotlib=3.0.3
  - tqdm=4.65.0
  - pip
  - pip:
    - dgl
    - torch-geometric==2.1.0
    - wandb
